### ISSUE TITLE
Unsupported MIME type: image/x-icon

### ISSUE THREAD

**Issue by Kikobeats** [Vibrant-Colors/node-vibrant#79]
I noted that icons are not supported:

```bash
Unsupported MIME type: image/x-icon
ERR TypeError: Cannot read property 'bitmap' of undefined
    at NodeImage.getWidth (/Users/josefranciscoverdugambin/Projects/microlink/splashy/node_modules/node-vibrant/lib/image/node.js:101:24)
    at NodeImage.ImageBase.scaleDown (/Users/josefranciscoverdugambin/Projects/microlink/splashy/node_modules/node-vibrant/lib/image/base.js:8:26)
    at Vibrant._process (/Users/josefranciscoverdugambin/Projects/microlink/splashy/node_modules/node-vibrant/lib/vibrant.js:22:15)
    at /Users/josefranciscoverdugambin/Projects/microlink/splashy/node_modules/node-vibrant/lib/vibrant.js:38:51
    at tryCatcher (/Users/josefranciscoverdugambin/Projects/microlink/splashy/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/josefranciscoverdugambin/Projects/microlink/splashy/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/josefranciscoverdugambin/Projects/microlink/splashy/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/josefranciscoverdugambin/Projects/microlink/splashy/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/josefranciscoverdugambin/Projects/microlink/splashy/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Users/josefranciscoverdugambin/Projects/microlink/splashy/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/josefranciscoverdugambin/Projects/microlink/splashy/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/josefranciscoverdugambin/Projects/microlink/splashy/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/josefranciscoverdugambin/Projects/microlink/splashy/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

That's okay but could be possible to avoid print the message in the terminal?

Also, ideally need a way to avoid the error, just failing silently, I mean, if it's not possible to resolve the icon, then return an empty object for following the workflow and avoid break the code.

**Comment by crutchcorn** [comment]
Is this error bubbled up properly? (IE, is it passed to the `catch` conditional)

If not, that's a bug and I'd love to take a look at it. Otherwise, simply use a `catch` to the promise to catch that error

**Comment by crutchcorn** [comment]
Closing, as this doesn't seem to be something we should edgecase
